# Deployment para la web app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-bmi-calc
spec:
  replicas: 3
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1 # Máximo número de pods que pueden estar no disponibles durante la actualización
    maxSurge: 1       # Máximo número de pods adicionales que se pueden crear temporalmente
  selector:
    matchLabels:
      app: spring-bmi-calc
  template:
    metadata:
      labels:
        app: spring-bmi-calc
    spec:
      containers:
      - name: spring-bmi-calc
        image: gabvillacis93/spring-bmi-calc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests: 
            memory: "256Mi" # Solicita esta cantidad de memoria
            cpu: "500m" # Solicita esta cantidad de CPU (0.5vcpu)
          limits:
            memory: "512Mi" # Limita a esta cantidad de memoria
            cpu: "1" # Limita a esta cantidad de CPU (1vcpu)      
---
# Servicio para la web app
apiVersion: v1
kind: Service
metadata:
  name: spring-bmi-calc-service
spec:
  selector:
    app: spring-bmi-calc
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer