name: CD Spring Web App - Deploy to Amazon EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Amazon EKS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name ${{ secret.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
      
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/deploy.yml

      - name: Force Rolling Update
        run: kubectl rollout update restart deployment spring-bmi-calc