name: Deploy to Amazon EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Amazon EKS
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace variables in deploy.yml (Kubernetes Specs)  
        run: |
          export DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}
          envsubst < k8s/deploy.yaml > k8s/deploy_updated.yaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl delete -f k8s/deploy_updated.yaml || true
          kubectl apply -f k8s/deploy_updated.yaml