name: CD Spring Web App

on: 
  workflow_dispatch:

  schedule:
    - cron: '15 2 5 9 *' # Se debe programar en base a UTC

jobs:

  deploy:
    #needs: build-and-publish # Requiere que termine primero termine build-and-publish

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          script: |
            docker stop spring-bmi-calc
            docker rm spring-bmi-calc
            docker run --pull always -d -p 80:8000 --name spring-bmi-calc gabvillacis93/spring-bmi-calc:latest