name: CI/CD Spring Web App

on:
  push:
    branches: [main]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
        
      - name: Install Maven dependencies
        run: mvn install -DskipTests
      
      - name: Run test & Generate Jar Package
        run: mvn --batch-mode verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gabvillacis93/spring-bmi-calc:latest
    
  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest 
    
    steps:
      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: | 
            docker stop spring-bmi-calc
            docker rm spring-bmi-calc
            docker run --pull always -d -p 80:8000 --name spring-bmi-calc gabvillacis93/spring-bmi-calc:latest